export const allyCasterConfig = {
  id: "ally-caster",
  name: "Ember Arcanist",
  team: "friendly",
  role: "caster",
  control: "ai",

  stats: {
    maxHealth: 1180,
    moveSpeed: 184,
    radius: 19,
    hitChance: 0.93,
    critChance: 0.17,
    dodgeChance: 0.04,
    critMultiplier: 1.5,
  },

  resource: {
    type: "mana",
    max: 100,
    start: 100,
    regenPerSecond: 5,
  },

  ai: {
    preferredRange: 300,
    targetPriorityRoles: ["caster", "melee", "healer"],
    ccTargetRoles: ["healer", "caster"],
    oomHealerFocusPct: 0.10,
    repositionWhenHealerControlled: true,
    healerLosPullDistance: 125,
  },

  spells: [
    {
      id: "arcanist-brand",
      name: "Ember Brand",
      target: "enemy",
      resourceCost: 12,
      castMs: 0,
      cooldownMs: 7000,
      gcdMs: 1200,
      range: 360,
      effects: [{ kind: "dot", amount: 48, durationMs: 8000, tickMs: 2000 }],
    },
    {
      id: "arcanist-chain",
      name: "Arc Chain",
      target: "enemy",
      resourceCost: 17,
      castMs: 1000,
      cooldownMs: 0,
      gcdMs: 1200,
      range: 360,
      effects: [{
        kind: "chainDamage",
        amount: 82,
        range: 360,
        maxTargets: 3,
        multipliers: [1, 0.72, 0.55],
        visualStyle: "lightning",
      }],
    },
    {
      id: "arcanist-lance",
      name: "Sun Lance",
      target: "enemy",
      resourceCost: 24,
      castMs: 2050,
      cooldownMs: 4500,
      gcdMs: 1200,
      range: 360,
      effects: [{ kind: "damage", amount: 176 }],
    },
    {
      id: "arcanist-comet",
      name: "Comet Seal",
      target: "enemy",
      resourceCost: 30,
      castMs: 1200,
      cooldownMs: 14000,
      gcdMs: 1200,
      range: 360,
      effects: [{ kind: "damage", amount: 240 }],
    },
    {
      id: "arcanist-trance",
      name: "Ember Trance",
      target: "enemy",
      school: "magic",
      utility: true,
      aiRole: "control",
      resourceCost: 18,
      castMs: 1500,
      cooldownMs: 18000,
      gcdMs: 1200,
      range: 340,
      noHitRoll: true,
      effects: [
        { kind: "incapacitate", durationMs: 4500, breakOnDamage: true },
      ],
    },
  ],
};
