export const deathKnightGear = Object.freeze({
  classId: "death-knight",
  displayName: "Death Knight",
  set: Object.freeze({
    id: "arena-gravewarden",
    name: "Arena Gravewarden",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% damage and self-healing.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["damage", "dot", "heal"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Mind Freeze cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "dk-mind-freeze", field: "cooldownMs", amount: -2000, min: 4000 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Runic Power regeneration and +3% maximum Health.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "maxHealth", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "dk-gravewarden-head",
      name: "Arena Gravewarden Helm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 190,
      setId: "arena-gravewarden",
      stats: { stamina: 48, criticalStrike: 0.006 },
    },
    {
      id: "dk-gravewarden-shoulders",
      name: "Arena Gravewarden Pauldrons",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 170,
      setId: "arena-gravewarden",
      stats: { stamina: 42, power: 0.017 },
    },
    {
      id: "dk-gravewarden-chest",
      name: "Arena Gravewarden Battleplate",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 230,
      setId: "arena-gravewarden",
      stats: { stamina: 68, resolve: 0.015 },
    },
    {
      id: "dk-gravewarden-hands",
      name: "Arena Gravewarden Gauntlets",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 150,
      setId: "arena-gravewarden",
      stats: { stamina: 34, haste: 0.008 },
    },
    {
      id: "dk-gravewarden-legs",
      name: "Arena Gravewarden Legplates",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 210,
      setId: "arena-gravewarden",
      stats: { stamina: 60, power: 0.018 },
    },
    {
      id: "dk-gravewarden-feet",
      name: "Arena Gravewarden Greaves",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 150,
      setId: "arena-gravewarden",
      stats: { stamina: 42, resolve: 0.010 },
    },
    {
      id: "dk-gravewarden-weapon",
      name: "Gravewarden Runeblade",
      slot: "weapon",
      slotLabel: "Two-Hand Runeblade",
      rankRequired: 1,
      cost: 380,
      stats: { power: 0.036, criticalStrike: 0.008 },
    },

    {
      id: "dk-veteran-feet",
      name: "Veteran Gravewarden Greaves",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 260,
      setId: "arena-gravewarden",
      upgradeFrom: "dk-gravewarden-feet",
      stats: { stamina: 58, resolve: 0.015 },
    },
    {
      id: "dk-veteran-hands",
      name: "Veteran Gravewarden Gauntlets",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 310,
      setId: "arena-gravewarden",
      upgradeFrom: "dk-gravewarden-hands",
      stats: { stamina: 50, haste: 0.014 },
    },
    {
      id: "dk-veteran-shoulders",
      name: "Veteran Gravewarden Pauldrons",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 370,
      setId: "arena-gravewarden",
      upgradeFrom: "dk-gravewarden-shoulders",
      stats: { stamina: 64, power: 0.027 },
    },
    {
      id: "dk-veteran-legs",
      name: "Veteran Gravewarden Legplates",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 450,
      setId: "arena-gravewarden",
      upgradeFrom: "dk-gravewarden-legs",
      stats: { stamina: 88, power: 0.029, resolve: 0.008 },
    },
    {
      id: "dk-veteran-head",
      name: "Veteran Gravewarden Helm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 520,
      setId: "arena-gravewarden",
      upgradeFrom: "dk-gravewarden-head",
      stats: { stamina: 78, criticalStrike: 0.010, resolve: 0.010 },
    },
    {
      id: "dk-veteran-chest",
      name: "Veteran Gravewarden Battleplate",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 620,
      setId: "arena-gravewarden",
      upgradeFrom: "dk-gravewarden-chest",
      stats: { stamina: 108, power: 0.014, resolve: 0.023 },
    },
    {
      id: "dk-elite-weapon",
      name: "Elite Gravewarden Runeblade",
      slot: "weapon",
      slotLabel: "Two-Hand Runeblade",
      rankRequired: 14,
      cost: 1100,
      upgradeFrom: "dk-gravewarden-weapon",
      stats: { power: 0.056, criticalStrike: 0.012, haste: 0.006 },
      spellModifiers: [
        { spellId: "dk-frost-strike", kind: "damage", scale: 0.05 },
        { spellId: "dk-death-strike", kind: "damage", scale: 0.05 },
        { spellId: "dk-death-strike", kind: "heal", scale: 0.05 },
      ],
    },
  ]),
});
