export const druidGear = Object.freeze({
  classId: "druid",
  displayName: "Druid",
  set: Object.freeze({
    id: "arena-grovewarden",
    name: "Arena Grovewarden",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% healing and damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["heal", "hot", "damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Ironbark cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "druid-ironbark", field: "cooldownMs", amount: -2000, min: 8000 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Mana regeneration and +3% movement speed.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "moveSpeed", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "druid-grovewarden-head",
      name: "Arena Grovewarden Helm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-grovewarden",
      stats: { stamina: 34, criticalStrike: 0.007 },
    },
    {
      id: "druid-grovewarden-shoulders",
      name: "Arena Grovewarden Spaulders",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-grovewarden",
      stats: { stamina: 30, power: 0.017 },
    },
    {
      id: "druid-grovewarden-chest",
      name: "Arena Grovewarden Tunic",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-grovewarden",
      stats: { stamina: 50, resolve: 0.012 },
    },
    {
      id: "druid-grovewarden-hands",
      name: "Arena Grovewarden Handguards",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-grovewarden",
      stats: { stamina: 24, haste: 0.010 },
    },
    {
      id: "druid-grovewarden-legs",
      name: "Arena Grovewarden Legguards",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-grovewarden",
      stats: { stamina: 44, power: 0.017 },
    },
    {
      id: "druid-grovewarden-feet",
      name: "Arena Grovewarden Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-grovewarden",
      stats: { stamina: 30, resolve: 0.008 },
    },
    {
      id: "druid-grovewarden-weapon",
      name: "Grovewarden Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 1,
      cost: 650,
      stats: { power: 0.034, haste: 0.009 },
    },

    {
      id: "druid-veteran-feet",
      name: "Veteran Grovewarden Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-grovewarden",
      upgradeFrom: "druid-grovewarden-feet",
      stats: { stamina: 42, resolve: 0.012 },
    },
    {
      id: "druid-veteran-hands",
      name: "Veteran Grovewarden Handguards",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-grovewarden",
      upgradeFrom: "druid-grovewarden-hands",
      stats: { stamina: 36, haste: 0.016 },
    },
    {
      id: "druid-veteran-shoulders",
      name: "Veteran Grovewarden Spaulders",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-grovewarden",
      upgradeFrom: "druid-grovewarden-shoulders",
      stats: { stamina: 46, power: 0.027 },
    },
    {
      id: "druid-veteran-legs",
      name: "Veteran Grovewarden Legguards",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-grovewarden",
      upgradeFrom: "druid-grovewarden-legs",
      stats: { stamina: 66, power: 0.029, resolve: 0.006 },
    },
    {
      id: "druid-veteran-head",
      name: "Veteran Grovewarden Helm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-grovewarden",
      upgradeFrom: "druid-grovewarden-head",
      stats: { stamina: 58, criticalStrike: 0.011, haste: 0.006 },
    },
    {
      id: "druid-veteran-chest",
      name: "Veteran Grovewarden Tunic",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-grovewarden",
      upgradeFrom: "druid-grovewarden-chest",
      stats: { stamina: 82, power: 0.014, resolve: 0.020 },
    },
    {
      id: "druid-elite-weapon",
      name: "Elite Grovewarden Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 14,
      cost: 5500,
      upgradeFrom: "druid-grovewarden-weapon",
      stats: { power: 0.048, haste: 0.014, criticalStrike: 0.005 },
      spellModifiers: [
        { spellId: "druid-regrowth", kind: "heal", scale: 0.05 },
        { spellId: "druid-regrowth", kind: "hot", scale: 0.05 },
        { spellId: "druid-moonfire", kind: "damage", scale: 0.05 },
        { spellId: "druid-moonfire", kind: "dot", scale: 0.05 },
      ],
    },
  ]),
});
