export const mageGear = Object.freeze({
  classId: "mage",
  displayName: "Mage",
  set: Object.freeze({
    id: "arena-spellweaver",
    name: "Arena Spellweaver",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Frost Nova cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "mage-frost-nova", field: "cooldownMs", amount: -2000, min: 7500 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Mana regeneration and +3% movement speed.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "moveSpeed", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "mage-spellweaver-head",
      name: "Arena Spellweaver Hood",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-spellweaver",
      stats: { stamina: 28, criticalStrike: 0.010 },
    },
    {
      id: "mage-spellweaver-shoulders",
      name: "Arena Spellweaver Mantle",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-spellweaver",
      stats: { stamina: 24, power: 0.020 },
    },
    {
      id: "mage-spellweaver-chest",
      name: "Arena Spellweaver Robe",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-spellweaver",
      stats: { stamina: 42, resolve: 0.010 },
    },
    {
      id: "mage-spellweaver-hands",
      name: "Arena Spellweaver Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-spellweaver",
      stats: { stamina: 20, haste: 0.012 },
    },
    {
      id: "mage-spellweaver-legs",
      name: "Arena Spellweaver Leggings",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-spellweaver",
      stats: { stamina: 36, power: 0.020 },
    },
    {
      id: "mage-spellweaver-feet",
      name: "Arena Spellweaver Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-spellweaver",
      stats: { stamina: 24, resolve: 0.007 },
    },
    {
      id: "mage-spellweaver-weapon",
      name: "Spellweaver Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 1,
      cost: 650,
      stats: { power: 0.038, haste: 0.010 },
    },

    {
      id: "mage-veteran-feet",
      name: "Veteran Spellweaver Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-spellweaver",
      upgradeFrom: "mage-spellweaver-feet",
      stats: { stamina: 34, resolve: 0.011 },
    },
    {
      id: "mage-veteran-hands",
      name: "Veteran Spellweaver Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-spellweaver",
      upgradeFrom: "mage-spellweaver-hands",
      stats: { stamina: 30, haste: 0.018 },
    },
    {
      id: "mage-veteran-shoulders",
      name: "Veteran Spellweaver Mantle",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-spellweaver",
      upgradeFrom: "mage-spellweaver-shoulders",
      stats: { stamina: 38, power: 0.030 },
    },
    {
      id: "mage-veteran-legs",
      name: "Veteran Spellweaver Leggings",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-spellweaver",
      upgradeFrom: "mage-spellweaver-legs",
      stats: { stamina: 54, power: 0.032, resolve: 0.005 },
    },
    {
      id: "mage-veteran-head",
      name: "Veteran Spellweaver Hood",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-spellweaver",
      upgradeFrom: "mage-spellweaver-head",
      stats: { stamina: 46, criticalStrike: 0.014, haste: 0.007 },
    },
    {
      id: "mage-veteran-chest",
      name: "Veteran Spellweaver Robe",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-spellweaver",
      upgradeFrom: "mage-spellweaver-chest",
      stats: { stamina: 68, power: 0.017, resolve: 0.018 },
    },
    {
      id: "mage-elite-weapon",
      name: "Elite Spellweaver Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 14,
      cost: 5500,
      upgradeFrom: "mage-spellweaver-weapon",
      stats: { power: 0.055, haste: 0.015, criticalStrike: 0.008 },
      spellModifiers: [
        { spellId: "mage-frostfire-bolt", kind: "damage", scale: 0.05 },
        { spellId: "mage-arcane-barrage", kind: "damage", scale: 0.05 },
      ],
    },
  ]),
});
