export const paladinGear = Object.freeze({
  classId: "paladin",
  displayName: "Paladin",
  set: Object.freeze({
    id: "arena-lightwarden",
    name: "Arena Lightwarden",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% healing and damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["heal", "hot", "damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Blessing of Protection cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "paladin-blessing", field: "cooldownMs", amount: -2000, min: 9000 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Mana regeneration and +3% maximum Health.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "maxHealth", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "paladin-lightwarden-head",
      name: "Arena Lightwarden Greathelm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-lightwarden",
      stats: { stamina: 42, criticalStrike: 0.006 },
    },
    {
      id: "paladin-lightwarden-shoulders",
      name: "Arena Lightwarden Pauldrons",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-lightwarden",
      stats: { stamina: 36, power: 0.017 },
    },
    {
      id: "paladin-lightwarden-chest",
      name: "Arena Lightwarden Breastplate",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-lightwarden",
      stats: { stamina: 60, resolve: 0.014 },
    },
    {
      id: "paladin-lightwarden-hands",
      name: "Arena Lightwarden Gauntlets",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-lightwarden",
      stats: { stamina: 30, haste: 0.009 },
    },
    {
      id: "paladin-lightwarden-legs",
      name: "Arena Lightwarden Legplates",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-lightwarden",
      stats: { stamina: 52, power: 0.017 },
    },
    {
      id: "paladin-lightwarden-feet",
      name: "Arena Lightwarden Greaves",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-lightwarden",
      stats: { stamina: 36, resolve: 0.010 },
    },
    {
      id: "paladin-lightwarden-mainhand",
      name: "Lightwarden War Mace",
      slot: "mainHand",
      slotLabel: "Main Hand",
      rankRequired: 1,
      cost: 350,
      stats: { power: 0.030, haste: 0.007 },
    },
    {
      id: "paladin-lightwarden-offhand",
      name: "Lightwarden Aegis",
      slot: "offHand",
      slotLabel: "Shield",
      rankRequired: 1,
      cost: 300,
      stats: { stamina: 34, resolve: 0.012, criticalStrike: 0.005 },
    },

    {
      id: "paladin-veteran-feet",
      name: "Veteran Lightwarden Greaves",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-lightwarden",
      upgradeFrom: "paladin-lightwarden-feet",
      stats: { stamina: 50, resolve: 0.015 },
    },
    {
      id: "paladin-veteran-hands",
      name: "Veteran Lightwarden Gauntlets",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-lightwarden",
      upgradeFrom: "paladin-lightwarden-hands",
      stats: { stamina: 44, haste: 0.015 },
    },
    {
      id: "paladin-veteran-shoulders",
      name: "Veteran Lightwarden Pauldrons",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-lightwarden",
      upgradeFrom: "paladin-lightwarden-shoulders",
      stats: { stamina: 56, power: 0.027 },
    },
    {
      id: "paladin-veteran-legs",
      name: "Veteran Lightwarden Legplates",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-lightwarden",
      upgradeFrom: "paladin-lightwarden-legs",
      stats: { stamina: 78, power: 0.029, resolve: 0.007 },
    },
    {
      id: "paladin-veteran-head",
      name: "Veteran Lightwarden Greathelm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-lightwarden",
      upgradeFrom: "paladin-lightwarden-head",
      stats: { stamina: 70, criticalStrike: 0.010, resolve: 0.009 },
    },
    {
      id: "paladin-veteran-chest",
      name: "Veteran Lightwarden Breastplate",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-lightwarden",
      upgradeFrom: "paladin-lightwarden-chest",
      stats: { stamina: 98, power: 0.014, resolve: 0.022 },
    },
    {
      id: "paladin-elite-mainhand",
      name: "Elite Lightwarden War Mace",
      slot: "mainHand",
      slotLabel: "Main Hand",
      rankRequired: 14,
      cost: 3000,
      upgradeFrom: "paladin-lightwarden-mainhand",
      stats: { power: 0.046, haste: 0.012, criticalStrike: 0.005 },
      spellModifiers: [
        { spellId: "paladin-word-of-glory", kind: "heal", scale: 0.05 },
        { spellId: "paladin-judgment", kind: "damage", scale: 0.05 },
      ],
    },
    {
      id: "paladin-elite-offhand",
      name: "Elite Lightwarden Aegis",
      slot: "offHand",
      slotLabel: "Shield",
      rankRequired: 14,
      cost: 2500,
      upgradeFrom: "paladin-lightwarden-offhand",
      stats: { stamina: 52, resolve: 0.016, power: 0.020 },
    },
  ]),
});
