export const priestGear = Object.freeze({
  classId: "priest",
  displayName: "Priest",
  set: Object.freeze({
    id: "arena-faithkeeper",
    name: "Arena Faithkeeper",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% healing and damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["heal", "hot", "damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Pain Suppression cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "priest-pain-suppression", field: "cooldownMs", amount: -2000, min: 8000 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Mana regeneration and +3% movement speed.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "moveSpeed", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "priest-faithkeeper-head",
      name: "Arena Faithkeeper Cowl",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-faithkeeper",
      stats: { stamina: 30, criticalStrike: 0.008 },
    },
    {
      id: "priest-faithkeeper-shoulders",
      name: "Arena Faithkeeper Mantle",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-faithkeeper",
      stats: { stamina: 26, power: 0.018 },
    },
    {
      id: "priest-faithkeeper-chest",
      name: "Arena Faithkeeper Robe",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-faithkeeper",
      stats: { stamina: 46, resolve: 0.012 },
    },
    {
      id: "priest-faithkeeper-hands",
      name: "Arena Faithkeeper Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-faithkeeper",
      stats: { stamina: 22, haste: 0.010 },
    },
    {
      id: "priest-faithkeeper-legs",
      name: "Arena Faithkeeper Leggings",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-faithkeeper",
      stats: { stamina: 40, power: 0.018 },
    },
    {
      id: "priest-faithkeeper-feet",
      name: "Arena Faithkeeper Sandals",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-faithkeeper",
      stats: { stamina: 26, resolve: 0.008 },
    },
    {
      id: "priest-faithkeeper-weapon",
      name: "Faithkeeper Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 1,
      cost: 650,
      stats: { power: 0.035, haste: 0.008 },
    },

    {
      id: "priest-veteran-feet",
      name: "Veteran Faithkeeper Sandals",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-faithkeeper",
      upgradeFrom: "priest-faithkeeper-feet",
      stats: { stamina: 38, resolve: 0.012 },
    },
    {
      id: "priest-veteran-hands",
      name: "Veteran Faithkeeper Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-faithkeeper",
      upgradeFrom: "priest-faithkeeper-hands",
      stats: { stamina: 34, haste: 0.016 },
    },
    {
      id: "priest-veteran-shoulders",
      name: "Veteran Faithkeeper Mantle",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-faithkeeper",
      upgradeFrom: "priest-faithkeeper-shoulders",
      stats: { stamina: 42, power: 0.028 },
    },
    {
      id: "priest-veteran-legs",
      name: "Veteran Faithkeeper Leggings",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-faithkeeper",
      upgradeFrom: "priest-faithkeeper-legs",
      stats: { stamina: 60, power: 0.030, resolve: 0.006 },
    },
    {
      id: "priest-veteran-head",
      name: "Veteran Faithkeeper Cowl",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-faithkeeper",
      upgradeFrom: "priest-faithkeeper-head",
      stats: { stamina: 52, criticalStrike: 0.012, haste: 0.006 },
    },
    {
      id: "priest-veteran-chest",
      name: "Veteran Faithkeeper Robe",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-faithkeeper",
      upgradeFrom: "priest-faithkeeper-chest",
      stats: { stamina: 76, power: 0.015, resolve: 0.020 },
    },
    {
      id: "priest-elite-weapon",
      name: "Elite Faithkeeper Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 14,
      cost: 5500,
      upgradeFrom: "priest-faithkeeper-weapon",
      stats: { power: 0.050, haste: 0.012, criticalStrike: 0.006 },
      spellModifiers: [
        { spellId: "priest-greater-heal", kind: "heal", scale: 0.05 },
        { spellId: "priest-smite", kind: "damage", scale: 0.05 },
        { spellId: "priest-holy-fire", kind: "damage", scale: 0.05 },
        { spellId: "priest-holy-fire", kind: "dot", scale: 0.05 },
      ],
    },
  ]),
});
