export const rogueGear = Object.freeze({
  classId: "rogue",
  displayName: "Rogue",
  set: Object.freeze({
    id: "arena-nightstalker",
    name: "Arena Nightstalker",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Kidney Shot cooldown reduced by 1.5s.",
        effects: [
          { type: "spellFieldAdd", spellId: "rogue-kidney", field: "cooldownMs", amount: -1500, min: 4000 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Energy regeneration and +3% movement speed.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "moveSpeed", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "rogue-nightstalker-head",
      name: "Arena Nightstalker Hood",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 180,
      setId: "arena-nightstalker",
      stats: { stamina: 35, criticalStrike: 0.008 },
    },
    {
      id: "rogue-nightstalker-shoulders",
      name: "Arena Nightstalker Shoulders",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 160,
      setId: "arena-nightstalker",
      stats: { stamina: 30, power: 0.018 },
    },
    {
      id: "rogue-nightstalker-chest",
      name: "Arena Nightstalker Tunic",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 220,
      setId: "arena-nightstalker",
      stats: { stamina: 50, resolve: 0.012 },
    },
    {
      id: "rogue-nightstalker-hands",
      name: "Arena Nightstalker Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 140,
      setId: "arena-nightstalker",
      stats: { stamina: 25, criticalStrike: 0.006 },
    },
    {
      id: "rogue-nightstalker-legs",
      name: "Arena Nightstalker Legguards",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 200,
      setId: "arena-nightstalker",
      stats: { stamina: 45, power: 0.018 },
    },
    {
      id: "rogue-nightstalker-feet",
      name: "Arena Nightstalker Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 140,
      setId: "arena-nightstalker",
      stats: { stamina: 30, resolve: 0.008 },
    },
    {
      id: "rogue-nightstalker-mainhand",
      name: "Nightstalker Shiv",
      slot: "mainHand",
      slotLabel: "Main Hand",
      rankRequired: 1,
      cost: 220,
      stats: { power: 0.025, criticalStrike: 0.008 },
    },
    {
      id: "rogue-nightstalker-offhand",
      name: "Nightstalker Left Blade",
      slot: "offHand",
      slotLabel: "Off Hand",
      rankRequired: 1,
      cost: 180,
      stats: { power: 0.018, criticalStrike: 0.006 },
    },

    {
      id: "rogue-veteran-feet",
      name: "Veteran Nightstalker Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 250,
      setId: "arena-nightstalker",
      upgradeFrom: "rogue-nightstalker-feet",
      stats: { stamina: 42, resolve: 0.012 },
    },
    {
      id: "rogue-veteran-hands",
      name: "Veteran Nightstalker Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 300,
      setId: "arena-nightstalker",
      upgradeFrom: "rogue-nightstalker-hands",
      stats: { stamina: 38, criticalStrike: 0.010 },
    },
    {
      id: "rogue-veteran-shoulders",
      name: "Veteran Nightstalker Shoulders",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 360,
      setId: "arena-nightstalker",
      upgradeFrom: "rogue-nightstalker-shoulders",
      stats: { stamina: 45, power: 0.028 },
    },
    {
      id: "rogue-veteran-legs",
      name: "Veteran Nightstalker Legguards",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 430,
      setId: "arena-nightstalker",
      upgradeFrom: "rogue-nightstalker-legs",
      stats: { stamina: 65, power: 0.030, resolve: 0.006 },
    },
    {
      id: "rogue-veteran-head",
      name: "Veteran Nightstalker Hood",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 500,
      setId: "arena-nightstalker",
      upgradeFrom: "rogue-nightstalker-head",
      stats: { stamina: 55, criticalStrike: 0.012, resolve: 0.008 },
    },
    {
      id: "rogue-veteran-chest",
      name: "Veteran Nightstalker Tunic",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 600,
      setId: "arena-nightstalker",
      upgradeFrom: "rogue-nightstalker-chest",
      stats: { stamina: 80, power: 0.015, resolve: 0.020 },
    },
    {
      id: "rogue-elite-mainhand",
      name: "Elite Nightstalker Shiv",
      slot: "mainHand",
      slotLabel: "Main Hand",
      rankRequired: 14,
      cost: 750,
      upgradeFrom: "rogue-nightstalker-mainhand",
      stats: { power: 0.040, criticalStrike: 0.012 },
      spellModifiers: [
        { spellId: "rogue-eviscerate", kind: "damage", scale: 0.05 },
      ],
    },
    {
      id: "rogue-elite-offhand",
      name: "Elite Nightstalker Left Blade",
      slot: "offHand",
      slotLabel: "Off Hand",
      rankRequired: 14,
      cost: 650,
      upgradeFrom: "rogue-nightstalker-offhand",
      stats: { power: 0.030, criticalStrike: 0.010 },
    },
  ]),
});
