export const shamanGear = Object.freeze({
  classId: "shaman",
  displayName: "Shaman",
  set: Object.freeze({
    id: "arena-stormcaller",
    name: "Arena Stormcaller",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["damage", "dot", "chainDamage"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Wind Shear cooldown reduced by 1.5s.",
        effects: [
          { type: "spellFieldAdd", spellId: "shaman-wind-shear", field: "cooldownMs", amount: -1500, min: 3500 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Mana regeneration and +3% movement speed.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "moveSpeed", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "shaman-stormcaller-head",
      name: "Arena Stormcaller Headdress",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-stormcaller",
      stats: { stamina: 32, criticalStrike: 0.008 },
    },
    {
      id: "shaman-stormcaller-shoulders",
      name: "Arena Stormcaller Shoulderguards",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-stormcaller",
      stats: { stamina: 28, power: 0.018 },
    },
    {
      id: "shaman-stormcaller-chest",
      name: "Arena Stormcaller Hauberk",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-stormcaller",
      stats: { stamina: 48, resolve: 0.012 },
    },
    {
      id: "shaman-stormcaller-hands",
      name: "Arena Stormcaller Grips",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-stormcaller",
      stats: { stamina: 24, haste: 0.010 },
    },
    {
      id: "shaman-stormcaller-legs",
      name: "Arena Stormcaller Legguards",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-stormcaller",
      stats: { stamina: 42, power: 0.018 },
    },
    {
      id: "shaman-stormcaller-feet",
      name: "Arena Stormcaller Sabatons",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-stormcaller",
      stats: { stamina: 28, resolve: 0.008 },
    },
    {
      id: "shaman-stormcaller-mainhand",
      name: "Stormcaller Warhammer",
      slot: "mainHand",
      slotLabel: "Main Hand",
      rankRequired: 1,
      cost: 350,
      stats: { power: 0.028, haste: 0.008 },
    },
    {
      id: "shaman-stormcaller-offhand",
      name: "Stormcaller Ward",
      slot: "offHand",
      slotLabel: "Off Hand",
      rankRequired: 1,
      cost: 300,
      stats: { power: 0.018, criticalStrike: 0.008 },
    },

    {
      id: "shaman-veteran-feet",
      name: "Veteran Stormcaller Sabatons",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-stormcaller",
      upgradeFrom: "shaman-stormcaller-feet",
      stats: { stamina: 40, resolve: 0.012 },
    },
    {
      id: "shaman-veteran-hands",
      name: "Veteran Stormcaller Grips",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-stormcaller",
      upgradeFrom: "shaman-stormcaller-hands",
      stats: { stamina: 36, haste: 0.016 },
    },
    {
      id: "shaman-veteran-shoulders",
      name: "Veteran Stormcaller Shoulderguards",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-stormcaller",
      upgradeFrom: "shaman-stormcaller-shoulders",
      stats: { stamina: 44, power: 0.028 },
    },
    {
      id: "shaman-veteran-legs",
      name: "Veteran Stormcaller Legguards",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-stormcaller",
      upgradeFrom: "shaman-stormcaller-legs",
      stats: { stamina: 62, power: 0.030, resolve: 0.006 },
    },
    {
      id: "shaman-veteran-head",
      name: "Veteran Stormcaller Headdress",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-stormcaller",
      upgradeFrom: "shaman-stormcaller-head",
      stats: { stamina: 54, criticalStrike: 0.012, haste: 0.006 },
    },
    {
      id: "shaman-veteran-chest",
      name: "Veteran Stormcaller Hauberk",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-stormcaller",
      upgradeFrom: "shaman-stormcaller-chest",
      stats: { stamina: 78, power: 0.015, resolve: 0.020 },
    },
    {
      id: "shaman-elite-mainhand",
      name: "Elite Stormcaller Warhammer",
      slot: "mainHand",
      slotLabel: "Main Hand",
      rankRequired: 14,
      cost: 3000,
      upgradeFrom: "shaman-stormcaller-mainhand",
      stats: { power: 0.045, haste: 0.012 },
      spellModifiers: [
        { spellId: "shaman-lava-burst", kind: "damage", scale: 0.05 },
        { spellId: "shaman-stormstrike", kind: "damage", scale: 0.05 },
      ],
    },
    {
      id: "shaman-elite-offhand",
      name: "Elite Stormcaller Ward",
      slot: "offHand",
      slotLabel: "Off Hand",
      rankRequired: 14,
      cost: 2500,
      upgradeFrom: "shaman-stormcaller-offhand",
      stats: { power: 0.030, criticalStrike: 0.012, resolve: 0.008 },
    },
  ]),
});
