export const warlockGear = Object.freeze({
  classId: "warlock",
  displayName: "Warlock",
  set: Object.freeze({
    id: "arena-dreadweaver",
    name: "Arena Dreadweaver",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Unending Resolve cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "warlock-resolve", field: "cooldownMs", amount: -2000, min: 9000 },
        ],
      },
      {
        pieces: 6,
        description: "+5% Mana regeneration and +3% maximum Health.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.05 },
          { type: "statFieldScale", field: "maxHealth", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "warlock-dreadweaver-head",
      name: "Arena Dreadweaver Hood",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-dreadweaver",
      stats: { stamina: 34, criticalStrike: 0.008 },
    },
    {
      id: "warlock-dreadweaver-shoulders",
      name: "Arena Dreadweaver Mantle",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-dreadweaver",
      stats: { stamina: 30, power: 0.019 },
    },
    {
      id: "warlock-dreadweaver-chest",
      name: "Arena Dreadweaver Robe",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-dreadweaver",
      stats: { stamina: 52, resolve: 0.013 },
    },
    {
      id: "warlock-dreadweaver-hands",
      name: "Arena Dreadweaver Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-dreadweaver",
      stats: { stamina: 26, haste: 0.010 },
    },
    {
      id: "warlock-dreadweaver-legs",
      name: "Arena Dreadweaver Leggings",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-dreadweaver",
      stats: { stamina: 46, power: 0.019 },
    },
    {
      id: "warlock-dreadweaver-feet",
      name: "Arena Dreadweaver Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-dreadweaver",
      stats: { stamina: 32, resolve: 0.009 },
    },
    {
      id: "warlock-dreadweaver-weapon",
      name: "Dreadweaver Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 1,
      cost: 650,
      stats: { power: 0.036, haste: 0.009 },
    },

    {
      id: "warlock-veteran-feet",
      name: "Veteran Dreadweaver Boots",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-dreadweaver",
      upgradeFrom: "warlock-dreadweaver-feet",
      stats: { stamina: 46, resolve: 0.013 },
    },
    {
      id: "warlock-veteran-hands",
      name: "Veteran Dreadweaver Gloves",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-dreadweaver",
      upgradeFrom: "warlock-dreadweaver-hands",
      stats: { stamina: 40, haste: 0.016 },
    },
    {
      id: "warlock-veteran-shoulders",
      name: "Veteran Dreadweaver Mantle",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-dreadweaver",
      upgradeFrom: "warlock-dreadweaver-shoulders",
      stats: { stamina: 50, power: 0.029 },
    },
    {
      id: "warlock-veteran-legs",
      name: "Veteran Dreadweaver Leggings",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-dreadweaver",
      upgradeFrom: "warlock-dreadweaver-legs",
      stats: { stamina: 72, power: 0.031, resolve: 0.007 },
    },
    {
      id: "warlock-veteran-head",
      name: "Veteran Dreadweaver Hood",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-dreadweaver",
      upgradeFrom: "warlock-dreadweaver-head",
      stats: { stamina: 62, criticalStrike: 0.012, haste: 0.006 },
    },
    {
      id: "warlock-veteran-chest",
      name: "Veteran Dreadweaver Robe",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-dreadweaver",
      upgradeFrom: "warlock-dreadweaver-chest",
      stats: { stamina: 88, power: 0.015, resolve: 0.021 },
    },
    {
      id: "warlock-elite-weapon",
      name: "Elite Dreadweaver Staff",
      slot: "weapon",
      slotLabel: "Two-Hand Staff",
      rankRequired: 14,
      cost: 5500,
      upgradeFrom: "warlock-dreadweaver-weapon",
      stats: { power: 0.052, haste: 0.013, criticalStrike: 0.006 },
      spellModifiers: [
        { spellId: "warlock-drain-life", kind: "damage", scale: 0.05 },
        { spellId: "warlock-drain-life", kind: "heal", scale: 0.05 },
        { spellId: "warlock-conflagrate", kind: "damage", scale: 0.05 },
      ],
    },
  ]),
});
