export const warriorGear = Object.freeze({
  classId: "warrior",
  displayName: "Warrior",
  set: Object.freeze({
    id: "arena-warbringer",
    name: "Arena Warbringer",
    bonuses: Object.freeze([
      {
        pieces: 2,
        description: "+4% damage.",
        effects: [
          { type: "allSpellEffectScale", kinds: ["damage", "dot"], scale: 0.04 },
        ],
      },
      {
        pieces: 4,
        description: "Charge cooldown reduced by 2s.",
        effects: [
          { type: "spellFieldAdd", spellId: "warrior-charge", field: "cooldownMs", amount: -2000, min: 5000 },
        ],
      },
      {
        pieces: 6,
        description: "+8% Rage regeneration and +3% maximum Health.",
        effects: [
          { type: "resourceFieldScale", field: "regenPerSecond", scale: 0.08 },
          { type: "statFieldScale", field: "maxHealth", scale: 0.03, integer: true },
        ],
      },
    ]),
  }),
  items: Object.freeze([
    {
      id: "warrior-warbringer-head",
      name: "Arena Warbringer Greathelm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 1,
      cost: 500,
      setId: "arena-warbringer",
      stats: { stamina: 45, criticalStrike: 0.006 },
    },
    {
      id: "warrior-warbringer-shoulders",
      name: "Arena Warbringer Pauldrons",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 1,
      cost: 450,
      setId: "arena-warbringer",
      stats: { stamina: 38, power: 0.016 },
    },
    {
      id: "warrior-warbringer-chest",
      name: "Arena Warbringer Battleplate",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 1,
      cost: 650,
      setId: "arena-warbringer",
      stats: { stamina: 62, resolve: 0.014 },
    },
    {
      id: "warrior-warbringer-hands",
      name: "Arena Warbringer Gauntlets",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 1,
      cost: 300,
      setId: "arena-warbringer",
      stats: { stamina: 32, haste: 0.008 },
    },
    {
      id: "warrior-warbringer-legs",
      name: "Arena Warbringer Legplates",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 1,
      cost: 600,
      setId: "arena-warbringer",
      stats: { stamina: 55, power: 0.018 },
    },
    {
      id: "warrior-warbringer-feet",
      name: "Arena Warbringer Greaves",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 1,
      cost: 300,
      setId: "arena-warbringer",
      stats: { stamina: 38, resolve: 0.010 },
    },
    {
      id: "warrior-warbringer-weapon",
      name: "Warbringer Greatblade",
      slot: "weapon",
      slotLabel: "Two-Hand Weapon",
      rankRequired: 1,
      cost: 650,
      stats: { power: 0.035, criticalStrike: 0.008 },
    },

    {
      id: "warrior-veteran-feet",
      name: "Veteran Warbringer Greaves",
      slot: "feet",
      slotLabel: "Feet",
      rankRequired: 3,
      cost: 650,
      setId: "arena-warbringer",
      upgradeFrom: "warrior-warbringer-feet",
      stats: { stamina: 52, resolve: 0.015 },
    },
    {
      id: "warrior-veteran-hands",
      name: "Veteran Warbringer Gauntlets",
      slot: "hands",
      slotLabel: "Hands",
      rankRequired: 5,
      cost: 1400,
      setId: "arena-warbringer",
      upgradeFrom: "warrior-warbringer-hands",
      stats: { stamina: 46, haste: 0.014 },
    },
    {
      id: "warrior-veteran-shoulders",
      name: "Veteran Warbringer Pauldrons",
      slot: "shoulders",
      slotLabel: "Shoulders",
      rankRequired: 7,
      cost: 2700,
      setId: "arena-warbringer",
      upgradeFrom: "warrior-warbringer-shoulders",
      stats: { stamina: 58, power: 0.026 },
    },
    {
      id: "warrior-veteran-legs",
      name: "Veteran Warbringer Legplates",
      slot: "legs",
      slotLabel: "Legs",
      rankRequired: 9,
      cost: 4200,
      setId: "arena-warbringer",
      upgradeFrom: "warrior-warbringer-legs",
      stats: { stamina: 80, power: 0.028, resolve: 0.007 },
    },
    {
      id: "warrior-veteran-head",
      name: "Veteran Warbringer Greathelm",
      slot: "head",
      slotLabel: "Head",
      rankRequired: 11,
      cost: 6000,
      setId: "arena-warbringer",
      upgradeFrom: "warrior-warbringer-head",
      stats: { stamina: 72, criticalStrike: 0.010, resolve: 0.009 },
    },
    {
      id: "warrior-veteran-chest",
      name: "Veteran Warbringer Battleplate",
      slot: "chest",
      slotLabel: "Chest",
      rankRequired: 13,
      cost: 8000,
      setId: "arena-warbringer",
      upgradeFrom: "warrior-warbringer-chest",
      stats: { stamina: 100, power: 0.014, resolve: 0.022 },
    },
    {
      id: "warrior-elite-weapon",
      name: "Elite Warbringer Greatblade",
      slot: "weapon",
      slotLabel: "Two-Hand Weapon",
      rankRequired: 14,
      cost: 5500,
      upgradeFrom: "warrior-warbringer-weapon",
      stats: { power: 0.055, criticalStrike: 0.012 },
      spellModifiers: [
        { spellId: "warrior-slam", kind: "damage", scale: 0.05 },
      ],
    },
  ]),
});
