export const enemyMeleeConfig = {
  id: "enemy-melee",
  name: "Ash Reaver",
  team: "enemy",
  role: "melee",
  control: "ai",

  stats: {
    maxHealth: 1410,
    moveSpeed: 202,
    radius: 21,
    hitChance: 0.90,
    critChance: 0.15,
    dodgeChance: 0.08,
    critMultiplier: 1.5,
  },

  resource: {
    type: "energy",
    max: 100,
    start: 100,
    regenPerSecond: 14,
  },

  ai: {
    preferredRange: 52,
    targetPriorityRoles: ["caster", "melee", "healer"],
  },

  spells: [
    {
      id: "reaver-wound",
      name: "Ash Wound",
      target: "enemy",
      resourceCost: 20,
      castMs: 0,
      cooldownMs: 7000,
      gcdMs: 1200,
      range: 58,
      effects: [{ kind: "dot", amount: 43, durationMs: 8000, tickMs: 2000 }],
    },
    {
      id: "reaver-slice",
      name: "Fast Slice",
      target: "enemy",
      resourceCost: 18,
      castMs: 0,
      cooldownMs: 0,
      gcdMs: 1200,
      range: 58,
      effects: [{ kind: "damage", amount: 74 }],
    },
    {
      id: "reaver-cleave",
      name: "Heavy Cleave",
      target: "enemy",
      resourceCost: 35,
      castMs: 1300,
      cooldownMs: 4500,
      gcdMs: 1200,
      range: 62,
      effects: [{ kind: "damage", amount: 154 }],
    },
    {
      id: "reaver-execution",
      name: "Execution Mark",
      target: "enemy",
      resourceCost: 45,
      castMs: 0,
      cooldownMs: 13500,
      gcdMs: 1200,
      range: 62,
      effects: [{ kind: "damage", amount: 216 }],
    },
    {
      id: "reaver-interrupt",
      name: "Skullbreaker",
      target: "enemy",
      school: "physical",
      utility: true,
      aiRole: "interrupt",
      resourceCost: 10,
      castMs: 0,
      cooldownMs: 10000,
      gcdMs: 0,
      ignoreGcd: true,
      range: 70,
      noHitRoll: true,
      effects: [{ kind: "interrupt", durationMs: 3000 }],
    },
  ],
};
